# Copyright 2023-2024 The SapientML Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release

on:
  push:
    tags:
      - '*.*.*'

env:
  POETRY_VERSION: "1.5.1"
  POETRY_URL: https://install.python-poetry.org

jobs:
  test:
    strategy:
      matrix:
        version: ["3.10", "3.11"]
        test: [test_sapientml_works_with, test_sapientml_raises_error, test_misc,
          test_regressor_works_number, test_regressor_works_with_nosparse,
          test_classifier_category_binary_num_noproba, test_classifier_category_binary_num_proba,
          test_classifier_category_multi_nonnum_metric_noproba, test_classifier_category_multi_nonnum_metric_proba,
          test_classifier_category_binary_boolean_metric_noproba, test_classifier_category_binary_boolean_metric_proba,
          test_classifier_category_binary_num_use_proba_with_metric_default_noproba, test_classifier_category_multi_nonnum_noproba_metric_with_proba,
          test_classifier_notext_nonegative_explanatry, test_classifier_works_with,
          test_explain, test_nan_or_inf_in_target_columns
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}

      - name: Install Poetry
        run: |
          curl -sSL ${{ env.POETRY_URL }} | python - --version ${{ env.POETRY_VERSION }}
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install mecab
        run: sudo apt install -y mecab libmecab-dev mecab-ipadic-utf8

      - name: Set up mecab
        run: sudo cp /etc/mecabrc /usr/local/etc/

      - name: Install Packages
        run: sudo apt install -y graphviz

      - name: Install Dependencies
        run: poetry install

      - name: Pytest
        run: poetry run -- pytest -k ${{ matrix.test }}
      
      - name: Upload Coverage
        uses: actions/upload-artifact@v3
        with:
          name:  ${{ matrix.test }}
          include-hidden-files: true
          path: .coverage
          retention-days: 1

  additional_test:
    strategy:
      matrix:
        version: ["3.10", "3.11"]
        test: [test_additional_misc,
          test_additional_regressor_works_number, test_additional_regressor_works_with_nosparse,
          test_additional_classifier_category_binary_nonnum_noproba, test_additional_classifier_category_binary_nonnum_proba,
          test_additional_classifier_category_binary_num_noproba, test_additional_classifier_category_binary_num_proba,
          test_additional_classifier_category_multi_nonnum_metric_noproba, test_additional_classifier_category_multi_nonnum_metric_proba,
          test_additional_classifier_category_multi_num_metric_noproba, test_additional_classifier_category_multi_num_metric_proba,
          test_additional_classifier_category_binary_boolean_metric_noproba, test_additional_classifier_category_binary_boolean_metric_proba,
          test_additional_classifier_category_binary_num_use_proba_with_metric_default_noproba, test_additional_classifier_category_multi_nonnum_noproba_metric_with_proba,
          test_additional_classifier_works_with
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}

      - name: Install Poetry
        run: |
          curl -sSL ${{ env.POETRY_URL }} | python - --version ${{ env.POETRY_VERSION }}
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install mecab
        run: sudo apt install -y mecab libmecab-dev mecab-ipadic-utf8

      - name: Set up mecab
        run: sudo cp /etc/mecabrc /usr/local/etc/

      - name: Install Packages
        run: sudo apt install -y graphviz

      - name: Install Dependencies
        run: poetry install

      - name: Pytest
        run: poetry run -- pytest -k ${{ matrix.test }}

      - name: Upload Coverage
        uses: actions/upload-artifact@v3
        with:
          name:  ${{ matrix.test }}
          include-hidden-files: true
          path: .coverage
          retention-days: 1

  report_coverage:
    runs-on: ubuntu-latest
    needs:
      - test
      - additional_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Download Coverage Files
        uses: actions/download-artifact@v3

      - name: Install coverage
        run: pip install coverage

      - name: Combine Coverage Files
        run: |
          mv --backup=t */.coverage .
          coverage combine -a
          coverage report

      - name: Report Coverage to CodeCov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - test
      - additional_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y

      - name: Update PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Set Version
        run: |
          SAPIENTML_VERSION=$(git describe --exact-match --tags HEAD)
          sed -i "s/\(version *= *\).*/\1\"$SAPIENTML_VERSION\"/" pyproject.toml

      - name: Build project for distribution
        run: poetry build

      - name: Check Version
        id: check-version
        run: |
          [[ "$(poetry version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || echo prerelease=true >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: steps.check-version.outputs.prerelease == 'true'

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --skip-existing